const position = [
    {
        id: 1,
        company: "Microsoft",
        logo: "icon",
        newPost: "2022",
        position: "Software Engineer",
        role: "Frontend",
        level: "Intermediate",
        contract: "Full time",
        location: "Remote",
        tools: "git, github, JetBrains IDEs",
        languages: "English, Japanese and Spanish",
    },{
        id: 2,
        company: "Google",
        logo: "icon",
        newPost: "2021",
        position: "Software Engineer",
        role: "NodeJS developer",
        level: "Intermediate",
        contract: "part time",
        location: "Remote",
        tools: "git, github, vs code",
        languages: "English",
    },{
        id: 3,
        company: "Amazon",
        logo: "icon",
        newPost: "2022",
        position: "Cloud arquitect",
        role: "AWS arquitect",
        level: "Advanced",
        contract: "Full time",
        location: "Remote",
        tools: "Linux, AWS",
        languages: "English and Spanish",
    }
]